language: node_js
node_js:
  - '8'
  - '10'
  - '12'
dist: trusty
addons:
  chrome: stable
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - openssl aes-256-cbc -K $encrypted_bbca46bf81cf_key -iv $encrypted_bbca46bf81cf_iv
    -in ./travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

install:
  - yarn install --no-lockfile --non-interactive

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - commitlint-travis
      - yarn run docs:publish
    on:
      branch: master
